[package]
name = "rusty_skelform"
version = "0.1.3.1"
edition = "2021"
description = "Generic SkelForm runtime for Rust"
license = "MIT"

[dependencies]
serde = {version = "1.0.217", features = ["derive"] }
